Repository jenkinsci/custom-war-packager, pull requests merged in 2020-07, with the labels that each got.

#162 Switch to GitHub-native Dependabot
  .github/dependabot.yml
Labels: chore

#161 Improve error message when Git tag or branch cannot be found + Update Jenkinsfile Runner Demo
  custom-war-packager-lib/src/main/java/io/jenkins/tools/warpackager/lib/impl/Builder.java
  custom-war-packager-lib/src/main/java/io/jenkins/tools/warpackager/lib/impl/jenkinsfileRunner/JenkinsfileRunnerDockerBuilder.java
  demo/jenkinsfile-runner/Makefile
  demo/jenkinsfile-runner/casc.yml
  demo/jenkinsfile-runner/demo/Jenkinsfile
  demo/jenkinsfile-runner/packager-config.yml
Labels: demo, enhancement

#167 Properly read the bomIncludeWar property
  custom-war-packager-lib/src/main/java/io/jenkins/tools/warpackager/lib/config/Config.java
Labels: bug
