Repository jenkinsci/custom-war-packager, pull requests merged in 2020-03, with the labels that each got.

#135 Fix support of the updateCenterUrl option
  Jenkinsfile
  custom-war-packager-cli/src/main/java/io/jenkins/tools/warpackager/cli/CliOptions.java
  custom-war-packager-cli/src/main/java/io/jenkins/tools/warpackager/cli/Main.java
  custom-war-packager-lib/src/main/java/io/jenkins/tools/warpackager/lib/config/BuildSettings.java
  custom-war-packager-lib/src/main/java/io/jenkins/tools/warpackager/lib/config/JenkinsRepositorySettings.java
  custom-war-packager-lib/src/main/java/io/jenkins/tools/warpackager/lib/impl/POMGenerator.java
Labels: bug, enhancement

#144 Add a cwp demo link
  README.md
Labels: documentation

#148 Add CODEOWNERS to automate reviews
  .github/CODEOWNERS
Labels: internal
